### ISSUE TITLE
Writing Unity3D Texture3D to NIfTI file

### ISSUE THREAD

**Issue by tlskillman** [plwp/Nifti.NET#1]
Thanks for making this code available. I have a Unity3D app that use the VolumeViewPro Unity Asset to load multiple NIfTI files and display them in VR. These images are viewed an manipulated leading to changes in the underlying image data. So now I want to write a new Texture3D back out as a new NIfTI file.  Not having any success yet...

I'm a middle level programmer so I may have missed some obvious way to use your NiftiFile.Write() routine. Texture3Ds are 3D array of Colors. After trying a number of variants, I can't figure out how to convert the Color array, nor what the proper datatype to use in your write file.

The error I get is:
```
System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Type,System.IO.Stream,object)
System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) (at <3e4da02cf86b4fc686ed0ac61bffc210>:0)
Nifti.NET.NiftiFile.Write (Nifti.NET.Nifti nifti, System.String path, System.Boolean gzip) (at Assets/NiftiFile.cs:78)
```
Any help greatly appreciated.

**Comment by plwp** [comment]
Hey, sounds like a really cool project!

The data should be stored as a uint (RGBA) and the heading needs to be set to the appropriate values for NIFTI_TYPE_RGBA32.

That said there may be an issue with the write function so I'll have a play around over the next couple days and try to come up with a helper function / example code.

Will get back to you.

Cheers,

Pat

**Comment by tlskillman** [comment]
Hi Pat,

Thanks for the info, and an example would be great! 

If you have access to VR equipment I can share my app with you. 

Best
Tom

**Comment by plwp** [comment]
I've updated NiftiFile.cs with a ConvertToRGB method which gets triggered if the data is of type Color[], which should let you write to a file. 

Support for RGBA is pretty bad in Nifti viewers so I've used RGB (which means you'll lose the alpha channel if you're using any transparency).

Let me know how you go.

( No VR hardware, sadly :( )

**Comment by tlskillman** [comment]
Hi Pat,

I'm struggling a bit to get your new code working.

There seems to be conflict between UnityEngine
Color(float,float,float,float) and Microsoft C# Color(byte,byte,byte). Once
I include your code in my Unity project it seems to interpret all your
Color() references a UnityEngine.

See https://docs.unity3d.com/ScriptReference/Color.html vs
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color?view=netframework-4.8

Here is the code that I'm using, and the error that it throws at run time.

Thanks,
Tom

----------CODE-----------

    public void WriteNii()
    {
        string fileDestination = channelList[0].filepath; // get where to
save the new nifti file
        string fileTemplate = channelList[0].filepath; // get another copy
of the Channel[0] to grab the nifti file data structure
        // Get an existing nifti file to use as template. Just replace the
image data.
        Nifti.NET.Nifti nifti = NiftiFile.Read(fileTemplate);

        // Get texture3d data
        Texture3D newData =
channelList[currentChannelIndex].ImageChannelGO.GetComponent<VolumeComponent>().data;
        // Convert the Texture3D into a Color32 array
        Color32[] newColorData = newData.GetPixels32();
        // Put the new Color32 data array into the Nifti object
        nifti.Data = newColorData;

        Debug.Log(nifti.Header.datatype);
        Debug.Log(nifti.Header.data_type);
        // And write out
        NiftiFile.Write(nifti, fileDestination + "-newBlend.nii");

        Console.Beep();
    }



---------ERROR----------

[image: image.png]

![image](https://user-images.githubusercontent.com/4645276/72654681-7368dc00-3945-11ea-8127-b805238d193c.png)

**Comment by tlskillman** [comment]
An example of the Color mixup is that your code throws an error about the "R" "G' and "B" vs "r" "g" and "b".

            for (int i = 0; i < data.Length; i+=3)
            {
                // Convert RGB to uint
                data[i] = nifti.Data[i / 3].r;
                data[i + 1] = nifti.Data[i / 3].g;
                data[i + 2] = nifti.Data[i / 3].b;
                //data[i] = nifti.Data[i / 3].R;
                //data[i + 1] = nifti.Data[i / 3].G;
                //data[i + 2] = nifti.Data[i / 3].B;
            }

**Comment by plwp** [comment]
Hi Tom,

I don't really want the library to depend on any Unity types if we can avoid it, but you should be able to just copy and paste the code to convert Color32[] to RBG24, e.g.:
```
public void WriteNii()
{
        string fileDestination = channelList[0].filepath; // get where to save the new nifti file
        string fileTemplate = channelList[0].filepath; // get another copy of the Channel[0] to grab the nifti file data structure
        // Get an existing nifti file to use as template. Just replace the image data.
        Nifti.NET.Nifti nifti = NiftiFile.Read(fileTemplate);

	// Might not need this if template is RGB, but just in case...
	nifti.Header.dim[0] = 5; // RGB and RGBA both have 5 dimensions
        nifti.Header.dim[4] = 1; 
        nifti.Header.dim[5] = 3; // 3 channels for RGB
        nifti.Header.bitpix = 24;
        nifti.Header.datatype = NiftiHeader.DT_RGB;
        nifti.Header.intent_code = NiftiHeader.NIFTI_INTENT_RGB_VECTOR;

        // Get texture3d data
        Texture3D newData = channelList[currentChannelIndex].ImageChannelGO.GetComponent<VolumeComponent>().data;
        // Convert the Texture3D into a Color32 array
        Color32[] newColorData = newData.GetPixels32();
        
	// Convert color32 data to bytes 
        var byteData = new byte[newColorData.Length * 3];
	for (int i = 0; i < byteData.Length; i+=3)
	{
		// Convert RGB to uint
		byteData[i] = newColorData[i/3].r;
		byteData[i+1] = newColorData[i/3].g;
		byteData[i+2] = newColorData[i/3].b;
	}
	nifti.Data = byteData;

        Debug.Log(nifti.Header.datatype);
        Debug.Log(nifti.Header.data_type);
        // And write out
        NiftiFile.Write(nifti, fileDestination + "-newBlend.nii");

        Console.Beep();
}
```

**Comment by tlskillman** [comment]
Hi Pat,

I see what your code does, and it runs without error, but when I read and then write out the same image data, I don't get a match. It seems that the byte packing just isn't right yet.  I ran the Unity debugger and the byte assignments from color seem right, but the write just isn't writing what I would expect. Sorry this is being a pain. I appreciate you taking the time to look at the issue. An example of the images before (left) and after (right) are below.

Tom

![image](https://user-images.githubusercontent.com/4645276/72659204-053a0e80-3971-11ea-9eaf-f11168505406.png)

**Comment by tlskillman** [comment]
Pat,

A little more debug info.  

I used your suggested code and made a run with the debugger to check what was happening in NiftiFile.Write.  The test you run on line 73, "if (typeof(Color[]) == nifti.Data.GetType())" returns false and skips the convertToRBG().  GetType() returns false because Color[] != Byte[]. It writes the Bytes out but gives that funny low-rez image that I sent in my previous post.  

Also, the file that gets written out is 1/3 larger than the original file. (65537KB vs 49153KB). But if I zoom out on the low rez image by a factor of 0.33 I get a reasonable image of a small section of the original, however it has some blue channel color and the original only had red and green.

![image](https://user-images.githubusercontent.com/4645276/72690894-7eeb0d00-3ad5-11ea-987f-1e884b04fe6a.png)  


I then tried just modifying my WriteNII() code to just read a nifti file and immediately write it back out. The file written was again 1/3 larger than the one I read, but I could open it in my nifti file viewer (NIH ImageJ) and it looked fine.

Thanks for any thoughts.

Tom

**Comment by plwp** [comment]
Hi Tom, 

RGB_24 nifti files should have 3 bytes per voxel. So if the image is 512x512x64, the length of newColorData should be 16,777,216, which means the length of byteData should be 50,331,648‬.

I can't see anywhere in NiftiFile.write that would modify the size so the output SHOULD be around 50MB. If it's 64MB then an extra byte is being added somewhere. 

The other possibility is that your viewer doesn't like 24bit encoding and is trying to read 4bytes per voxel, but that wouldn't explain the size difference.

Unfortunately I can't reproduce the problem on my end so if you have a nifti file which you can share (without any private info) that will trigger the bug that'd be a great help.

**Comment by tlskillman** [comment]
Hi Pat,

Yes, unclear what's going on.  Since the file growth happens even when I just read and immediately write the same Nifti object, maybe we're getting closer to the issues.

I've attached the image-stack which has been placed in the public domain by the scientist who created it, Craig Daly from Univ of Glasgow.

Thanks for taking a look.

Tom

[MMA_pressureFixCompV2 - Credit.zip](https://github.com/plwp/Nifti.NET/files/4087634/MMA_pressureFixCompV2.-.Credit.zip)

**Comment by plwp** [comment]
So it looks like your data is stored in planar format, meaning that the red, green and blue images are stored separately. This seems to be how the Analyze7.5 format does color (based on the fact that it works for most image viewers, and 90% of the time nifti will work as an analyze file). 

The nifti standard says that RGB values are stored with RGB triples at each voxel, which when read as planar data looks like what you're getting.

I've attached some code which can convert planar data to nifti RGB (it will overwrite the file so be careful), which you can view in BrainSuite (which will read color nifti's correctly).

If you'd rather keep your data in planar mode for easy viewing in ImageJ you can use the PlanarIndex method to write the data back out in your WriteNifti method.

```
        public void ConvertPlanar(string path)
        {
            // First we're going to read the file using the forceType tag to make sure we're not converting to System.drawing.Color
            var nii = NiftiFile.Read(path, forceType:NiftiHeader.DT_UNSIGNED_byte);
            // Get the x,y,z dims
            var xDim = nii.Header.dim[1];
            var yDim = nii.Header.dim[2];
            var zDim = nii.Header.dim[3];
            // New byte array to hold the data.
            var newData = new byte[nii.Data.Length];
            // Loop over in standard format
            for (int z = 0, i=0; z < zDim; ++z)
            {
                for (int y = 0; y < yDim; ++y)
                {
                    for (int x = 0; x < xDim && i <newData.Length; ++x)
                    {
                        newData[i++] = nii.Data[PlanarIndex(x, y, z, 0, nii.Header)]; // Red
                        newData[i++] = nii.Data[PlanarIndex(x, y, z, 1, nii.Header)]; // Green
                        newData[i++] = nii.Data[PlanarIndex(x, y, z, 2, nii.Header)]; // Blue
                    }
                }
            }

            // Save the modified file.
            nii.Data = newData;
            NiftiFile.Write(nii, path);
        }

        public static int PlanarIndex(int x, int y, int z, int rgb, NiftiHeader hdr)
        {
            return x + y * hdr.dim[1] + rgb * hdr.dim[1] * hdr.dim[2] + z * hdr.dim[1] * hdr.dim[2] * hdr.dim[5];
        }
```


"I'm I out of touch? No, it's the children who are wrong"

**Comment by tlskillman** [comment]
Hi Pat,

I'm still hammering on this problem. Your code was helpful but I was still getting weird results in the new nifti file.  

One thing I just figured out is the fact that Unity3D forces 2^n size dimensions on its Textures. So the .nii file I load is (560, 480, 20), but the Unity Texture32 is (512, 1024, 32). (Looks also like x and y are swapped.) The Color32[] that I get from the Texture32 is 16777216  which equals (512*1024*32). So by the time I get to your Nifiti code we're dealing with a completely different data beast. 

Now I know what to focus on.  Will keep you apprised.

Tom

PS - I also figured out how to include System.Drawing.Color() into my Unity project, so that may be useful as well.  The "Best Answer" on this page explains: https://answers.unity.com/questions/53170/using-drawing-package-like-systemdrawing.html
(Include this comment for future Unity coders running into this problem.)

**Comment by tlskillman** [comment]
Hi Pat,

So here's an update, and a question.  I'm very close now. 

When I reload the image, it's position in VR space is slightly offset (by 1) and scaled in z (by 3). This is probably in my code, but in debugging I found that in the new nifti file I write out the header block is written with swapped endian, compared to the initial file I loaded, but the data block isn't. Any idea why that would be?

Code and two file hex dumps are below.

Thanks,
Tom

--------- new WriteNii() ---------

    public void WriteNii()
    {
        string fileDestination = channelList[0].filepath; // get where to save the new nifti file
        string fileTemplate = channelList[0].filepath; // get another copy of the Channel[0] to grab the nifti file data structure
        // Get an existing nifti file to use as template. Just replace the image data.
        Nifti.NET.Nifti nifti = NiftiFile.Read(fileTemplate,forceType: NiftiHeader.DT_UNSIGNED_byte);

        //// Might not need this if template is RGB, but just in case...
        //nifti.Header.dim[0] = 5; // RGB and RGBA both have 5 dimensions
        //nifti.Header.dim[4] = 1;
        //nifti.Header.dim[5] = 1; // 3 channels for RGB
        //nifti.Header.bitpix = 24;
        //nifti.Header.datatype = NiftiHeader.DT_RGB;
        //nifti.Header.intent_code = NiftiHeader.NIFTI_INTENT_RGB_VECTOR;

        // Get texture3d data
        Texture3D newData = channelList[currentChannelIndex].ImageChannelGO.GetComponent<VolumeComponent>().data;
        // Convert the Texture3D into a Color32 array
        Color32[] newColorData = newData.GetPixels32();

        // Convert color32 data to bytes 
        var byteData = new byte[newColorData.Length * 3];
        for (int i = 0; i < byteData.Length; i += 3)
        {
            // Convert RGB to uint
            byteData[i] = newColorData[i / 3].r;
            byteData[i + 1] = newColorData[i / 3].g;
            byteData[i + 2] = newColorData[i / 3].b;
        }
        nifti.Data = byteData;

        // Now convert back to planar
        // Get the x,y,z dims
        var xDim = nifti.Header.dim[1];
        var yDim = nifti.Header.dim[2];
        var zDim = nifti.Header.dim[3];
        // New byte array to hold the data.
        var planarData = new byte[nifti.Data.Length];
        // Loop over in standard format
        for (int z = 0, i = 0; z < zDim; ++z)
        {
                for (int y = 0; y < yDim; ++y)
            {
                for (int x = 0; x < xDim && i < planarData.Length; ++x)
                {
                    planarData[PlanarIndex(x, y, z, 0, nifti.Header)] = nifti.Data[i++]; // Red
                    planarData[PlanarIndex(x, y, z, 1, nifti.Header)] = nifti.Data[i++]; // Red
                    planarData[PlanarIndex(x, y, z, 2, nifti.Header)] = nifti.Data[i++]; // Red
                }
            }
        }

        nifti.Data = planarData;

        Debug.Log(nifti.Header.datatype);
        Debug.Log(nifti.Header.data_type);
        // And write out
        NiftiFile.Write(nifti, fileDestination.Substring(0, fileDestination.Length - 4) +  "-newBlend.nii");

        Console.Beep();
    }

--------- Hex dump original (left) and new (right) ---------

![image](https://user-images.githubusercontent.com/4645276/73596970-7256b380-44dc-11ea-8264-ceed04ac5173.png)

**Comment by tlskillman** [comment]
Pat, 

Got it working!  I had commented out where you set dim[5]=3 because I didn't think that block of settings was needed, but wrong.  dim[5] was 1 coming in, but needed to be 3 when we wrote out. I tracked this down when I realized that in the hex dump of the nifti file I created, only about 1/3 of the data was filled in, the rest were 0000!  :-)     (As you say in your code "Oh, shit!")

I don't understand why the header block has the endinan swapped, but your code seems happy to plow through it, and interpret it all correctly.

So more testing to do, but first try seems good and I'm optimistic about getting the rest right.

FYI - I'm working with Confocal Microscope images, and those microscope take a series of 3D image-stacks, each time tuning the excitation laser to a different frequency in order to excite different sets of fluorophores that have been chemically bound to specific proteins of interest in a cell or tissue. Each scan produces a 3D intensity image (no color). So having one plane of the planar data format for each scan sort of makes sense. In the case of a 3-plane image-stack, it is useful to interpret the three planes as RGB so that the scientist can see the location of the different fluorescent makers by their different colors.  This is what I do in ImageJ. 

Thanks for your help, and your code. I like you coding style, clean and efficient.  Nice work.  

If I can do anything for you to promote your Git project, LMK.

Best,
Tom - www.immsci.com

**Comment by plwp** [comment]
Good to hear it's coming along.

The endianess will be saved in the local OS default, so if that is different to the original file it'll be swapped. The conversion happens when the bytes are cast to a type, but since we're skipping that step in the example code for the data then it won't be converted. If you need to convert it you can use BitConverter (lots of examples in NiftiFile).

Thanks for the feedback, glad to hear it's useful :)
