### ISSUE TITLE
Incorrect Import of unsigned short (uint16) datasets

### ISSUE THREAD

**Issue by Contused** [plwp/Nifti.NET#3]
When importing a uint16 dataset the library creates a data array twice the correct size. Furthermore the values inside the array are shifted. Both the dimensions and datatype are being read correctly from the header. The "forcetype" parameter does not seem to work.

I tested the same dataset inside a different application and it worked fine.

To recreate the problem you can use the "wallnut.nii.gz" dataset provided by the University of Leipzig, Germany:

http://www.informatik.uni-leipzig.de/~wiebel/public_data/index.html

They also have the open source software called "OpenWalnut" to display the dataset:

http://www.openwalnut.org/

Technical details:
-Nifti.Net is used as a dll for a C# Script in Unity 2019.4.12f11
-Nifti.Data.Length return twice the correct size of the imported dataset array
-Dimensions and datatype are correct
-forcetype parameter in Nifti.Read does not change the outcome
-You can iterate past the size of a dimension in the dataset
-Displaying the dataset shows that the values are shifted in a certain pattern
-uint8 datasets are working fine with the lib

**Comment by plwp** [comment]
Hi Alexander,

Thanks for the bug report, I'll try to have a look at it in the next couple of days.

**Comment by plwp** [comment]
Have (hopefully) added support for uint16 files as of version 1.1.2. 

Sorry about the delay. Please let me know how you go and I'll close the issue off.

**Comment by Contused** [comment]
Yes, now my data is imported correctly. Thank you very much for the fix!

**Comment by plwp** [comment]
Fantastic! Thanks for the detailed and easy to reproduce bug report.
