### ISSUE TITLE
Time frame , the length of each frame is different, how to deal with the NII format.

### ISSUE THREAD

**Issue by xxl-cc** [plwp/Nifti.NET#6]
Time frame, the length of each frame is different, how to deal with the NII format.
For example, the time of the first frame is 0-5s, and the time of the second frame is 5-25s。

**Comment by plwp** [comment]
Hi, 

I'm not sure if what the convention is in this case, but additional metadata can be stored in a JSON sidecar file, e.g.(https://bids.neuroimaging.io/).
